# Exported from Render on 2024-07-11T12:08:50Z
services:
- type: web
  name: MockTastic-backend
  runtime: node
  repo: https://github.com/NikeVictor/mockTastic
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm run dev
version: "1"
